name: Python tests

on:
  push:
    branches:
      - "develop"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install findspark pyspark mlflow boto3 fastapi pydantic pandas numpy uvicorn pytest
          pip install -U -e .
      - name: Integration tests with pytest
        run: |
          cd tests/
          pytest test.py
    
