name: Python tests

on:
  push:
    branches:
      - "develop"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Java
        run: |
          sudo apt-get update && \
          sudo apt-get install -y curl \
          wget \
          openjdk-8-jdk 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install findspark pyspark mlflow boto3 fastapi pydantic pandas numpy uvicorn pytest setuptools starlette-exporter httpx
      
      - name: Integration tests with pytest
        run: |
          pytest tests/test.py
    
